import { ROLES } from "./roles";

export const PERMISSIONS = {
  MANAGE_USER: "MANAGE_USER",
  MANAGE_SYLLABUS: "MANAGE_SYLLABUS",
  APPROVE_SYLLABUS: "APPROVE_SYLLABUS",
  VIEW_REPORT: "VIEW_REPORT",
};

export const ROLE_PERMISSIONS: Record<string, string[]> = {
  [ROLES.ADMIN]: [
    PERMISSIONS.MANAGE_USER,
    PERMISSIONS.MANAGE_SYLLABUS,
    PERMISSIONS.VIEW_REPORT,
  ],
  [ROLES.LECTURER]: [PERMISSIONS.MANAGE_SYLLABUS],
  [ROLES.HOD]: [PERMISSIONS.APPROVE_SYLLABUS],
  [ROLES.ACADEMIC]: [PERMISSIONS.APPROVE_SYLLABUS],
  [ROLES.PRINCIPAL]: [PERMISSIONS.VIEW_REPORT],
  [ROLES.STUDENT]: [],
};
